### ISSUE TITLE
Provide a link to the original post.

### ISSUE THREAD

**Issue by Totulik** [phrutis/wif500#2]
Provide a link to the original post.

**Comment by phrutis** [comment]
Do you need an original diary photo?

**Comment by g00dwin555** [comment]
Вы оставили сид фразу, поэтому смысла не было замазывать часть ключа, он восстанавливается за пару минут.

**Comment by g00dwin555** [comment]
column sea alone anchor escape amount apart coil between tail alley grow

**Comment by phrutis** [comment]
That key is useless, we are looking for another key.

**Comment by Smsu838** [comment]
Ого у Вас тут движ какой в погоне за 20 мультами зелени ))

**Comment by evgenyunholy** [comment]
Шо за движ?

**Comment by phrutis** [comment]
Погоня за 500 битками :)))

**Comment by Smsu838** [comment]
58^10 x 9 = 3877237862094652416 :face_with_spiral_eyes:

**Comment by evgenyunholy** [comment]
58^12. Фигня, на питоне быстро переберется)

**Comment by evgenyunholy** [comment]
Так а все таки, где оригинальный пост? Гугл по этому кошельку выдает автора с потеряными 5 символами.

**Comment by phrutis** [comment]
Видимо пока искал, потерял ещё 7

**Comment by jonlloner** [comment]
попробуй найти эти 5

**Comment by phrutis** [comment]
Кого 5 ? Посмотри на фото не хватает 12

**Comment by phrutis** [comment]
Какие 5 ? Посмотри на фото не хватает 12

**Comment by jonlloner** [comment]
кто автор оригинала?

**Comment by phrutis** [comment]
Аноним.
Судя транзакциям он вывел всё кроме этого адреса.

**Comment by Smsu838** [comment]
Участвовать в челенже надо когда останется диапазонов 10 и хорошо бы еще знать парольную фразу rsa 🤪

**Comment by evgenyunholy** [comment]
А что, тут не просто приватник>адрес?

**Comment by evgenyunholy** [comment]
И с чего вы взяли что тут 52 символа, а не 51?

**Comment by phrutis** [comment]
evgenyunholy без обид ты уже 153 эксперт. 
152 из них крутят сами 51 символ 5...  
Над WIF работали много понимающих в этом людей.
Для этого и сделан челлендж что бы люди крутили в правильном направлении.

Smsu838 это да, сейчас вяло, многие хотят наблюдать. Напоминает майнинг в 2011-м году.

**Comment by Ak535Ak** [comment]
> evgenyunholy без обид ты уже 153 эксперт. 152 из них крутят сами 51 символ 5... Над WIF работали много понимающих в этом людей. Для этого и сделан челлендж что бы люди крутили в правильном направлении.
> 
> Smsu838 это да, сейчас вяло, многие хотят наблюдать. Напоминает майнинг в 2011-м году.

Я пытаюсь запустить в соло через WifSolverCuda, так как моя карта не подходит под Ваши требования, но толи не правильно списал остатки wif толи еще что но если запускать через рандом то с первой буквой К выдает лютую скорость под 129.536 Gkey/s что явно указывает на проблему, если первая буква L то не стартует в принципе а вот с 5 полет нормальный  1.126 Gkey/s на 1660 super... Поэтому возможно опасения [evgenyunholy](https://github.com/evgenyunholy) не так уж и беспочвенны ?

**Comment by Smsu838** [comment]
Адрес сжатый, может иметь 9 вариантов начала, не хватает 10 букв что = 430804206899405824, скорость должна быть в зависимости от видеокарты но никак не 150 ) где то ошибка в написании и искать в соло практически не имеет смыла ))

**Comment by phrutis** [comment]
Smsu838 и у тебя ошибка. Почти каждый ищет не правильно.
12 символов
2*9*58*58*58*58*58*58*58*58*58*58 = 7754475724189304832

Нпглядно
7754475724189304832
  430804206899405824

**Comment by Ak535Ak** [comment]
> Адрес сжатый, может иметь 9 вариантов начала, не хватает 10 букв что = 430804206899405824, скорость должна быть в зависимости от видеокарты но никак не 150 ) где то ошибка в написании и искать в соло практически не имеет смыла ))

Это скорее технический интерес нежели попытка что то найти, объем для перебора понятен, не понятно было почему если указать вначале перебора при рандоме 5 все работает норм а при K или L нет.
./WifSolverCuda.exe -part1 5 -part2 5bCRZhiS5sEGMpmcRZdPAhmWLRfMmutGmPHtjVob -a 1PfNh5fRcE9JKDmicD2Rh3pexGwce1LqyU

**Comment by phrutis** [comment]
Smsu838 и у тебя ошибка. Почти каждый ищет не правильно.
12 символов
2 * 9 * 58 * 58 * 58 * 58 * 58 * 58 * 58 * 58 * 58 * 58 = 7754475724189304832


7,754.475,724,189,304,832
  430,804,206,899,405,824

**Comment by phrutis** [comment]
Ak535Ak Потому что у тебя ключ не правильный чексумма выдаёт e6 вместо 01, потому что буква не такая. и не в том режиме ищешь., + ещё 3 ощибки

**Comment by phrutis** [comment]
Там ещё с 10-ок мелких ньюансов, не буду всё озвучивать

**Comment by jonlloner** [comment]
Вы можете дать мне свой адрес электронной почты? У меня нет телеграма.

**Comment by phrutis** [comment]
Зачем вам адрес? Задайте ваш вопрос здесь.
Если что-то важное скачайте телеграм

**Comment by jonlloner** [comment]
с какой буквы начинается эта информация?

**Comment by phrutis** [comment]
L или K

**Comment by Smsu838** [comment]
Ну плюс минус километр быват )) там так то если смотреть по правильному то и начал не 9 а 8 но это опять же все лирика, пущай ищут кому интересно 🙈

**Comment by phrutis** [comment]
Там 9

**Comment by phrutis** [comment]
Малейшая ошибка приведёт к перебору пустоты, или несуществующих диапазонов.
Кто не хочет перебирать пустоту присоединяйтесь к челленджу. Если кому-то повезёт в выигрыше будут все охотники которые прошли диапазоны.
